"""Initial migration with updated models

Revision ID: 1f461e533985
Revises: 
Create Date: 2025-09-29 12:01:02.424913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f461e533985'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_code', sa.String(length=100), nullable=False),
    sa.Column('native_language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_participant_code'), ['participant_code'], unique=True)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_snippets', sa.Integer(), nullable=False),
    sa.Column('audio_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_video_id'), ['video_id'], unique=True)

    op.create_table('comprehension_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprehension_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprehension_responses_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprehension_responses_video_id'), ['video_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('snippet_index', sa.Integer(), nullable=False),
    sa.Column('keystroke_data', sa.JSON(), nullable=True),
    sa.Column('response_recording_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_video_id'), ['video_id'], unique=False)

    op.create_table('snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('snippet_index', sa.Integer(), nullable=False),
    sa.Column('video_filename', sa.String(length=200), nullable=False),
    sa.Column('audio_filename', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('transcript_original', sa.Text(), nullable=True),
    sa.Column('transcript_translated', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'snippet_index', name='unique_video_snippet')
    )
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.create_index('idx_video_snippet', ['video_id', 'snippet_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_snippets_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snippets_video_id'))
        batch_op.drop_index('idx_video_snippet')

    op.drop_table('snippets')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_video_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_participant_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('comprehension_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprehension_responses_video_id'))
        batch_op.drop_index(batch_op.f('ix_comprehension_responses_participant_id'))

    op.drop_table('comprehension_responses')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_video_id'))

    op.drop_table('videos')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_participant_code'))

    op.drop_table('participants')
    # ### end Alembic commands ###
