"""init schema

Revision ID: 97f802ec58fc
Revises: 
Create Date: 2025-11-06 21:18:43.102270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f802ec58fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_participants_participant_id'), ['participant_id'], unique=True)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_snippets', sa.Integer(), nullable=False),
    sa.Column('google_form_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('snippet_index', sa.Integer(), nullable=False),
    sa.Column('video_filename_full', sa.String(length=500), nullable=True),
    sa.Column('video_filename_muffled', sa.String(length=500), nullable=True),
    sa.Column('video_filename_balanced', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('transcript_original', sa.Text(), nullable=True),
    sa.Column('transcript_translated', sa.Text(), nullable=True),
    sa.Column('mcq_questions', sa.JSON(), nullable=True),
    sa.Column('is_calibration', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'snippet_index', name='unique_video_snippet')
    )
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.create_index('idx_video_snippet', ['video_id', 'snippet_index'], unique=False)

    op.create_table('volume_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('optimal_volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'video_id', name='unique_participant_video_calibration')
    )
    op.create_table('participant_audio_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('audio_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'snippet_id', name='unique_participant_snippet_audio')
    )
    op.create_table('snippet_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('audio_recording_path', sa.String(length=500), nullable=True),
    sa.Column('audio_recording_base64', sa.Text(), nullable=True),
    sa.Column('audio_mime_type', sa.String(length=50), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('mcq_answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'snippet_id', name='unique_participant_snippet_response')
    )
    with op.batch_alter_table('snippet_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snippet_responses_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snippet_responses_snippet_id'), ['snippet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snippet_responses_submitted_at'), ['submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippet_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snippet_responses_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_snippet_responses_snippet_id'))
        batch_op.drop_index(batch_op.f('ix_snippet_responses_participant_id'))

    op.drop_table('snippet_responses')
    op.drop_table('participant_audio_assignments')
    op.drop_table('volume_calibrations')
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.drop_index('idx_video_snippet')

    op.drop_table('snippets')
    op.drop_table('videos')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_participant_id'))
        batch_op.drop_index(batch_op.f('ix_participants_email'))

    op.drop_table('participants')
    # ### end Alembic commands ###
