"""Add video session tracking

Revision ID: da5ea4448fdb
Revises: 97f802ec58fc
Create Date: 2025-11-08 11:31:18.567092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5ea4448fdb'
down_revision = '97f802ec58fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'video_id', name='unique_participant_video_session')
    )
    with op.batch_alter_table('video_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_participant_video_session', ['participant_id', 'video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_participant_video_session')

    op.drop_table('video_sessions')
    # ### end Alembic commands ###
